feat: add "prepareIncreaseMultiple" and "prepareDecreaseMultiple" methods
calypsonet/calypsonet-terminal-calypso-java-api pull request #36
Opened 2022-01-05 18:54 UTC by jeanpierrefortune

Closes #23

2022-01-06 09:23 UTC, andrei-cristea requested changes

2022-01-06 09:23 UTC, andrei-cristea commented on src/main/java/org/calypsonet/terminal/calypso/transaction/CardTransactionManager.java
> +   * @throws IllegalArgumentException If one of the provided argument is out of range or
Si cette commande n'est pas gérée par les anciennes cartes, il faut rajouter l'exception `UnsupportedOperationException`.

2022-01-06 09:23 UTC, andrei-cristea commented on src/main/java/org/calypsonet/terminal/calypso/transaction/CardTransactionManager.java
> +  CardTransactionManager prepareIncreaseMultiple(byte sfi, int[] counterNumbers, int[] incValues);
On pourrait aussi utiliser une `Map<Integer, byte[]> counterNumberToIncValueMap`

2022-01-06 09:23 UTC, andrei-cristea commented on src/main/uml/api_class_diagram.puml
> +            +CardTransactionManager prepareIncreaseMultiple(byte sfi, int[] counterNumbers, int[] incValues)
D'abord increase, puis decrease

2022-01-07 08:34 UTC, jeanpierrefortune commented on src/main/java/org/calypsonet/terminal/calypso/transaction/CardTransactionManager.java
> +   * @throws IllegalArgumentException If one of the provided argument is out of range or
Oui

2022-01-07 08:34 UTC, jeanpierrefortune commented on src/main/uml/api_class_diagram.puml
> +            +CardTransactionManager prepareIncreaseMultiple(byte sfi, int[] counterNumbers, int[] incValues)
Fait

2022-01-07 08:35 UTC, jeanpierrefortune commented on src/main/java/org/calypsonet/terminal/calypso/transaction/CardTransactionManager.java
> +  CardTransactionManager prepareIncreaseMultiple(byte sfi, int[] counterNumbers, int[] incValues);
Changé en `Map<Integer, Integer> counterNumberToIncValueMap`

2022-01-07 09:18 UTC, andrei-cristea approved these changes

2022-01-07 09:19 UTC, merged