feat: add signature computation/verification features
calypsonet/calypsonet-terminal-calypso-java-api pull request #46
Opened 2022-02-21 11:27 UTC by andrei-cristea

Closes #28, closes #29

2022-02-22 05:32 UTC, pterr requested changes

2022-02-22 05:32 UTC, pterr commented on src/main/java/org/calypsonet/terminal/calypso/transaction/SignatureVerificationData.java
> +  boolean isSignatureValid();
During the data signature verification, if the traceability data is present, AND if a SamRevocationServiceSpi is defined => then the validity of the SAM which has generated the signature could be automatically checked.
If the SAM isn't valid an exception could be issued.

2022-02-22 05:32 UTC, pterr commented on src/main/java/org/calypsonet/terminal/calypso/transaction/SignatureVerificationData.java
> +  byte[] getSamTraceabilitySerialNumber();
For me, if the SamRevocationServiceSpi is automatically processed then:
 - getSamTraceabilitySerialNumber()
 - getSamTraceabilityKeyCounter()
are low-level command (not necessary for the terminal application)

2022-02-22 05:32 UTC, pterr commented on src/main/java/org/calypsonet/terminal/calypso/transaction/SignatureVerificationData.java
> +  SignatureVerificationData disableBusyMode();
To remove, the busy mode is defined only at the computation of the signature

2022-02-22 05:32 UTC, pterr commented on src/main/java/org/calypsonet/terminal/calypso/transaction/SamSecuritySetting.java
> +public interface SamSecuritySetting extends CommonSecuritySetting<SamSecuritySetting> {}
Here, we will certainely define in the future a method like:

SamSecuritySetting setControlSamResource (CardReader controlSamReader, CalypsoSam controlSam)

2022-02-22 09:09 UTC, andrei-cristea commented on src/main/java/org/calypsonet/terminal/calypso/transaction/SignatureComputationData.java
> +  SignatureComputationData useKeyDiversifier(byte[] keyDiversifier);
The documentation has been updated.

2022-02-22 11:08 UTC, andrei-cristea commented on src/main/java/org/calypsonet/terminal/calypso/transaction/SignatureVerificationData.java
> +  SignatureVerificationData useKeyDiversifier(byte[] keyDiversifier);
The documentation has been updated.

2022-02-24 12:50 UTC, pterr approved these changes

2022-02-24 14:27 UTC, merged